parcial 2/invetigaciones/invetigaciones/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trabajos.urls', namespace="trabajos")),
]

parcial 2/invetigaciones/trabajos/urls.py
from django.contrib import admin
from django.urls import path

from trabajos import views

app_name="trabajo"

urlpatterns = [
    path('',views.AllList.as_view(), name="index_view"),
    path('create/',views.Create.as_view(), name="create_document"),
    path('allList/',views.AllList.as_view(), name="list_all" ),
    path('listComp/',views.ListComp.as_view(), name="list_comp" ),
    path('listMed/',views.ListMed.as_view(), name="list_med" ),
    path('listNat/',views.ListNat.as_view(), name="list_nat" ),
    path('listSoc/',views.ListSoc.as_view(), name="list_soc" ),
    path('listTierra/',views.ListTierra.as_view(), name="list_tierra" ),
    path('update/<int:pk>', views.UpdateTrabajo.as_view(), name= "update_trabajo"),
    path('delete/<int:pk>', views.DeleteTrabajo.as_view(), name = "delete_trabajo"),
]

parcial 2/invetigaciones/trabajos/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Trabajo(models.Model):
    COMPUTACIONALES = 'CC'
    TIERRA = 'CT'
    NATURALES = 'CN'
    SOCIALES = 'CS'
    MEDICAS = 'CM'
    CATEGORIAS=(
        (COMPUTACIONALES, 'Ciencias Computacionales'),
        (TIERRA, 'Ciencias de la Tierra'),
        (NATURALES, 'Ciencias Naturales'),
        (SOCIALES, 'Ciencias Sociales'),
        (MEDICAS, 'Ciencias Medicas'),
    )
    documento = models.FileField(upload_to='documents/')
    categoria = models.CharField(max_length=2,choices=CATEGORIAS,default=COMPUTACIONALES)
    titulo = models.CharField(max_length=250)
    autor = models.CharField(max_length=250)
    timestamp=models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

parcial 2/invetigaciones/trabajos/forms.py
from django import forms
from .models import Trabajo

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Trabajo
        fields = ["documento", "titulo", "autor"]

parcial 2/invetigaciones/trabajos/views.py
from django.shortcuts import render
from .models import Trabajo
from .forms import DocumentForm
from django.views import generic
# Create your views here.

def index(request):
    context={
    "mensaje": "hola k ase",
    }
    return render(request,"tweets/index.html",context)

class Create(generic.CreateView):
    template_name = "trabajo/create.html"
    model = Trabajo
    fields = ["documento","categoria","titulo","autor"]
    success_url = "/allList/"

class AllList(generic.ListView):
    template_name = "trabajo/allList.html"
    model = Trabajo

class ListComp(generic.ListView):
    template_name = "trabajo/ListComp.html"
    model = Trabajo

class ListMed(generic.ListView):
    template_name = "trabajo/ListMed.html"
    model = Trabajo

class ListNat(generic.ListView):
    template_name = "trabajo/ListNat.html"
    model = Trabajo

class ListSoc(generic.ListView):
    template_name = "trabajo/ListSoc.html"
    model = Trabajo

class ListTierra(generic.ListView):
    template_name = "trabajo/ListTierra.html"
    model = Trabajo

class UpdateTrabajo(generic.UpdateView):
    template_name = "trabajo/update.html"
    model = Trabajo
    fields = ["categoria","titulo", "autor"]
    success_url = "/allList/"

class DeleteTrabajo(generic.DeleteView):
    template_name = "trabajo/delete.html"
    model = Trabajo
    success_url = "/allList/"

parcial 2/invetigaciones/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.min.css' %}">

    <title>{% block title %} {% endblock%}</title>
  </head>
  <body>

    {%include "navbar.html" %}

    {% block content%}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

parcial 2/invetigaciones/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'trabajos:list_all' %}">Investigaciones</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trabajos:list_comp' %}">Ciencias Computacionales</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trabajos:list_tierra' %}">Ciencias de la Tierra</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trabajos:list_nat' %}">Ciencias Naturales</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trabajos:list_soc' %}">Ciencias Sociales</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'trabajos:list_med' %}">Ciencias Medicas</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'trabajos:create_document' %}" class="btn btn-success">  Subir</a>
      </li>

    </ul>
  </div>
</nav>

parcial 2/invetigaciones/templates/trabajo/ListComp.html
{%extends "base.html"%}
{%block title%}Lista total{%endblock%}
{%block content%}
{% for trabajo in object_list %}
{% if trabajo.categoria == 'CC'%}
<div class="container justify-content-center">
  <div class="row ">
    <div class="col-md-6">
      <h4>Titulo de investigacion: {{ trabajo.titulo }} </h4>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-12">
      <ul>
        <li>Autor: {{ trabajo.autor }}</li>
        <li>Categoria: {{ trabajo.get_categoria_display}}</li>
      </ul>
      <a href="{% url 'trabajos:update_trabajo' trabajo.id %}" class="btn btn-primary">Actualizar</a>
      <a href="{% url 'trabajos:delete_trabajo' trabajo.id %}" class="btn btn-primary">Borrar</a>
      <hr>
    </div>
  </div>
</div>
{%endif%}
{% endfor %}
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/ListMed.html
{%extends "base.html"%}
{%block title%}Lista total{%endblock%}
{%block content%}
{% for trabajo in object_list %}
{% if trabajo.categoria == 'CM'%}
<div class="container justify-content-center">
  <div class="row ">
    <div class="col-md-6">
      <h4>Titulo de investigacion: {{ trabajo.titulo }} </h4>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-12">
      <ul>
        <li>Autor: {{ trabajo.autor }}</li>
        <li>Categoria: {{ trabajo.get_categoria_display}}</li>
      </ul>
      <a href="{% url 'trabajos:update_trabajo' trabajo.id %}" class="btn btn-primary">Actualizar</a>
      <a href="{% url 'trabajos:delete_trabajo' trabajo.id %}" class="btn btn-primary">Borrar</a>
      <hr>
    </div>
  </div>
</div>
{%endif%}
{% endfor %}
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/ListNat.html
{%extends "base.html"%}
{%block title%}Lista total{%endblock%}
{%block content%}
{% for trabajo in object_list %}
{% if trabajo.categoria == 'CN'%}
<div class="container justify-content-center">
  <div class="row ">
    <div class="col-md-6">
      <h4>Titulo de investigacion: {{ trabajo.titulo }} </h4>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-12">
      <ul>
        <li>Autor: {{ trabajo.autor }}</li>
        <li>Categoria: {{ trabajo.get_categoria_display}}</li>
      </ul>
      <a href="{% url 'trabajos:update_trabajo' trabajo.id %}" class="btn btn-primary">Actualizar</a>
      <a href="{% url 'trabajos:delete_trabajo' trabajo.id %}" class="btn btn-primary">Borrar</a>
      <hr>
    </div>
  </div>
</div>
{%endif%}
{% endfor %}
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/ListSoc.html
{%extends "base.html"%}
{%block title%}Lista total{%endblock%}
{%block content%}
{% for trabajo in object_list %}
{% if trabajo.categoria == 'CS'%}
<div class="container justify-content-center">
  <div class="row ">
    <div class="col-md-6">
      <h4>Titulo de investigacion: {{ trabajo.titulo }} </h4>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-12">
      <ul>
        <li>Autor: {{ trabajo.autor }}</li>
        <li>Categoria: {{ trabajo.get_categoria_display}}</li>
      </ul>
      <a href="{% url 'trabajos:update_trabajo' trabajo.id %}" class="btn btn-primary">Actualizar</a>
      <a href="{% url 'trabajos:delete_trabajo' trabajo.id %}" class="btn btn-primary">Borrar</a>
      <hr>
    </div>
  </div>
</div>
{%endif%}
{% endfor %}
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/ListTierra.html
{%extends "base.html"%}
{%block title%}Lista total{%endblock%}
{%block content%}
{% for trabajo in object_list %}
{% if trabajo.categoria == 'CT'%}
<div class="container justify-content-center">
  <div class="row ">
    <div class="col-md-6">
      <h4>Titulo de investigacion: {{ trabajo.titulo }} </h4>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-12">
      <ul>
        <li>Autor: {{ trabajo.autor }}</li>
        <li>Categoria: {{ trabajo.get_categoria_display}}</li>
      </ul>
      <a href="{% url 'trabajos:update_trabajo' trabajo.id %}" class="btn btn-primary">Actualizar</a>
      <a href="{% url 'trabajos:delete_trabajo' trabajo.id %}" class="btn btn-primary">Borrar</a>
      <hr>
    </div>
  </div>
</div>
{%endif%}
{% endfor %}
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/allList.html
{%extends "base.html"%}
{%block title%}Lista total{%endblock%}
{%block content%}
{% for trabajo in object_list %}
<div class="container justify-content-center">
  <div class="row ">
    <div class="col-md-6">
      <h4>Titulo de investigacion: {{ trabajo.titulo }} </h4>
    </div>
  </div>
  <div class="row ">
    <div class="col-md-12">
      <ul>
        <li>Autor: {{ trabajo.autor }}</li>
        <li>Categoria: {{ trabajo.get_categoria_display}}</li>
      </ul>
      <a href="{% url 'trabajos:update_trabajo' trabajo.id %}" class="btn btn-primary">Actualizar</a>
      <a href="{% url 'trabajos:delete_trabajo' trabajo.id %}" class="btn btn-primary">Borrar</a>
      <hr>
    </div>
  </div>
</div>

{% endfor %}
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/create.html
{%extends "base.html"%}
{%block title%}Subir trabajo{%endblock%}
{%block content%}

  <form method="POST" enctype="multipart/form-data">
    <div class="container">
      <div class="row">
        <div class="form-group">
          {% csrf_token %}

          <p>Seleccione su archivo: {{form.documento}} </p> <br>
          <p>Categoria: {{form.categoria}}</p><br>
          <p>Titulo de la investigacion: {{form.titulo}}</p><br>
          <p>Nombre del autor: {{form.autor}}</p>
          <input type="submit" name="create" value="Guardar" class="btn btn-primary">
        </div>
      </div>
    </div>

  </form>

{%endblock%}

parcial 2/invetigaciones/templates/trabajo/delete.html
{%extends "base.html"%}
{%block title%}Borrar{%endblock%}
{%block content%}
<form method="post">
  {% csrf_token %}

  <p>Desea borrar a investigacion: " {{object.titulo}} "?</p>
  <button type="submit" class="btn btn-primary">Borrar</button>
  <a href="{% url 'trabajos:list_all' %}" class="btn btn-primary">Regresar</a>

</form>
{%endblock%}

parcial 2/invetigaciones/templates/trabajo/update.html
{%extends "base.html"%}
{%block title%}Actualizar{%endblock%}
{%block content%}
  <form method="POST">
    <div class="container">
      <div class="row">
        <div class="form-group">
          {% csrf_token %}

          <p>Categoria: {{form.categoria}}</p><br>
          <p>Titulo de la investigacion: {{form.titulo}}</p><br>
          <p>Nombre del autor: {{form.autor}}</p>
          <input type="submit" name="create" value="Actualizar" class="btn btn-primary">
        </div>
      </div>
    </div>
  </form>
{%endblock%}