parcial 2/twitterclone/tweets/urls.py
from django.contrib import admin
from django.urls import path

from tweets import views

app_name="tweet"

urlpatterns = [
    path('',views.index, name="index_view"),
    path('list_tweets/', views.ListTweets.as_view(), name="list_tweets"),
    path('detail_tweet/<int:pk>/', views.DetailTweet.as_view(), name="detail_tweets"),
    path('create/',views.Create.as_view(), name="create_tweets"),
    path('update/<int:pk>', views.UpdateTweet.as_view(), name= "update_tweets"),
    path('delete/<int:pk>', views.DeleteTweet.as_view(), name = "delete_tweets"),
]

parcial 2/twitterclone/twitterclone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tweets.urls', namespace="tweets")),
]

if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

parcial 2/twitterclone/home/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    content= models.CharField(max_length=250)
    timestamp=models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

parcial 2/twitterclone/tweets/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    content= models.CharField(max_length=250)
    timestamp=models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

parcial 2/twitterclone/tweets/forms.py
from django import forms

from .models import Tweet

class FormCreate(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ["content"]

parcial 2/twitterclone/tweets/views.py
from django.shortcuts import render
from .models import Tweet
from .forms import FormCreate
from django.views import generic

# Create your views here.
def index(request):
    context={
    "mensaje": "hola k ase",
    "numerico": 23,
    "arreglo": [1,2,3,4],
    "dic": {"a": 12, "b":43}
    }
    return render(request,"tweets/index.html",context)


class ListTweets(generic.ListView):
    template_name="tweets/list_tweets.html"
    model = Tweet

def list_tweets(request):
#    queryset= Tweet.objects.all()
    context = {
        "tweets": Tweet.objects.all()
    }
    return render(request, "tweets/list_tweets.html", context)


class DetailTweet(generic.DetailView):
    template_name = "tweets/detail.html"
    model = Tweet

def detail_tweet(request, id=1):
    queryset = Tweet.objects.get(id=id)
    context = {
        "tweet_object": queryset
    }
    return render(request, "tweets/detail.html", context)


class Create(generic.CreateView):
    template_name = "tweets/create.html"
    model = Tweet
    fields = ["user", "content"]
    success_url = "/list_tweets/"

def create(request):
    form = FormCreate(request.POST or None)
    if request.POST:
        if form.is_valid():
            form.save()
    else:
        form = FormCreate(request.POST or None)
    context = {
    "form": form
    }
    return render(request, "tweets/create.html", context)

class UpdateTweet(generic.UpdateView):
    template_name = "tweets/update.html"
    model = Tweet
    fields = ["content"]
    success_url = "/list_tweets/"

class DeleteTweet(generic.DeleteView):
    template_name = "tweets/delete.html"
    model = Tweet
    success_url = "/list_tweets/"

parcial 2/twitterclone/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">TwitterClone</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">twitterClone<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

parcial 2/twitterclone/templates/tweets/create.html
<div class="row">
  <form method="POST">
      {% csrf_token %}
      {{form}}
      <input type="submit" name="create" value="Tweet">
  </form>
</div>

parcial 2/twitterclone/templates/tweets/delete.html
<form method="post">
  {% csrf_token %}

  <p>Desea borrar el Tweet: " {{object.content}} "?</p>
  <button type="submit">Delete</button>

</form>

parcial 2/twitterclone/templates/tweets/detail.html
<p>Usuario: {{ object.user }} </p>
<br>
<p>{{object.content}}</p>

<a href="{% url 'tweets:list_tweets' %}">Back</a>

parcial 2/twitterclone/templates/tweets/index.html
{% extends "base.html" %}
{% block title %}Index{%endblock%}
{% block content %}
  <button type="" class="btn btn-primary">hola</button>
{% endblock %}

parcial 2/twitterclone/templates/tweets/list_tweets.html
{%extends "base.html"%}
{%block title%}ListTweets{%endblock%}
{%block content%}
<ul>
  {% for tweet in object_list %}
  <li>{{ tweet.content }}</li>
  <a href="{% url 'tweets:detail_tweets' tweet.id %}">view</a>
  <a href="{% url 'tweets:update_tweets' tweet.id %}">Update</a>
  <a href="{% url 'tweets:delete_tweets' tweet.id %}">Delete</a>
  {% endfor %}

</ul>
{%endblock%}

parcial 2/twitterclone/templates/tweets/update.html
<div class="row">
  <form method="POST">
      {% csrf_token %}
      {{form}}
      <input type="submit" name="create" value="Tweet">
  </form>
</div>